# import nowych elementow z /imports : docker compose --profile cli up --abort-on-container-exit

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-v2}
    ports:
      - "2283:2283"
    env_file:
      - .env
    depends_on:
      - database
      - redis
    restart: unless-stopped
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - ${THUMB_LOCATION}:/data/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/data/encoded-video
      - ${PROFILE_LOCATION}:/data/profile
      - ${BACKUP_LOCATION}:/data/backups
      - ${IMPORTS_LOCATION}:/external:ro
      - /etc/localtime:/etc/localtime:ro

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-v2}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - model-cache:/cache
      - /etc/localtime:/etc/localtime:ro

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:15-vectorchord0.5.3
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME} -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  immich-cli:
    image: ghcr.io/immich-app/immich-cli:latest
    profiles: ["cli"]
    environment:
      IMMICH_INSTANCE_URL: ${IMMICH_INSTANCE_URL}
      IMMICH_API_KEY: ${IMMICH_API_KEY}
    volumes:
      - ${IMPORTS_LOCATION}:/import:ro
    command: >
      upload /import
      --recursive
      -c 5
    stdin_open: true
    tty: true
    depends_on:
      immich-server:
        condition: service_healthy


volumes:
  model-cache:
    name: immich_model_cache
    driver: local
